# Generated by Django 3.2.7 on 2021-12-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211218_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Front_Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('sub_title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Front Persons',
            },
        ),
    ]
