# Generated by Django 3.2.7 on 2021-12-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20211219_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='Concert', max_length=100),
            preserve_default=False,
        ),
    ]
